# -*- coding: utf-8 -*-
"""Data_Management_project_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJ1Wo7F4NBdXqYmWweAHiYAgvQirV5Ih

### Data management project report code by Toscani William and Morgan Vinciguerra

# Libraries
"""

!pip install ydata-profiling

from sqlalchemy import create_engine, text

import requests, time, json, os, re, zipfile
from io import BytesIO

from ydata_profiling import ProfileReport
import missingno as msno

import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
from shapely.geometry import shape
import plotly.graph_objects as go
from sklearn.cluster import KMeans

"""# Data acquisition e storage

## 1 Terna: electricity generation (by source)
"""

# Connecting to Neon database

engine = create_engine(
    'postgresql://neondb_owner:npg_KfpHzkTh2S8n@ep-proud-dust-a9m8vefx-pooler.gwc.azure.neon.tech/neondb?sslmode=require&channel_binding=require',
    echo=False,
)

# Connecting to Terna API (and get access token)

def GetTernaAccessToken(client_id, client_secret):
  token_url = "https://api.terna.it/public-api/access-token"
  payload = {'grant_type': 'client_credentials', 'client_id': f'{client_id}', 'client_secret': f'{client_secret}'}
  headers = {'Content-Type': 'application/x-www-form-urlencoded'}

  response = requests.post(token_url, headers=headers, data=payload).json()
  return response.get('access_token')

def GetTernaData(query_url, headers, params):
  response = requests.request("GET", query_url, headers=headers, params=params)
  response.raise_for_status()
  json_data = response.json()

  time.sleep(0.5) # sleep function
  return list(json_data.values())[1]

access_token = GetTernaAccessToken('fn7cycs695kp3qkt5n42rk5j', 'c5YwyrCP79')

# Downloading data (yearly JSON from 2005 to 2022)

endpoint_elec_by_type = "https://api.terna.it/generation/v2.0/electrical-energy-by-source"
headers = {'Authorization': f'Bearer {access_token}'}

all_data = []
for y in range(2005, 2023):
    print(f"Scarico anno {y}...")
    params = {"year": y}
    try:
        data = GetTernaData(endpoint_elec_by_type, headers, params)
        all_data.extend(data)
        print(f"{len(data)} record")
    except Exception as e:
        print(f"Errore per anno {y}: {e}")

print(f"\nTotale record scaricati: {len(all_data)}")

# Creating table in Neon (following the schema provived by Terna documentation)

with engine.begin() as conn:
  conn.execute(text("""
    CREATE TABLE IF NOT EXISTS back_tier.generation_y_r_p_s (
    year INTEGER,
    production_type TEXT,
    region TEXT,
    province TEXT,
    source TEXT,
    production_GWh DOUBLE PRECISION
  );
  """))

# Inserting data into table in Neon (performing a homogeneous pre-integration:
# from many yearly JSON files to unique JSON file)

json_payload = json.dumps(all_data)

with engine.begin() as conn:
    conn.execute(text("""
      INSERT INTO  back_tier.generation_y_r_p_s (
          year, production_type, region, province, source, production_gwh
      )
      SELECT
          year::integer,
          production_type,
          region,
          province,
          source,
          "production_GWh"::double precision
      FROM jsonb_to_recordset((:payload)::jsonb) AS t(
          year TEXT,
          production_type TEXT,
          region TEXT,
          province TEXT,
          source TEXT,
          "production_GWh" DOUBLE PRECISION
    );
    """), {"payload": json_payload})

"""## 2 EDGAR: ghg emissions (by sector)"""

# Download a ZIP file, cache it locally, list its contents, and read the "GHG by NUTS2 and Sector" sheet
# of the first Excel file found. Save it as a CSV and as a notebook variable.
# The cell now caches the ZIP under ./downloads/ and will not re-download unless `force_download=True`.
# Reads data starting from row 6 (header in row 6, 0-indexed as row 5).

# If `zip_url` already exists in the notebook, this reuses it; otherwise set it here.
try:
    zip_url  # if defined earlier, keep existing value
except NameError:
    zip_url = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/subnational_NUTS2/v80_FT2022_GHG_NUTS2_v2/EDGARv8.0_total_GHG_GWP100_AR5_NUTS2_1990_2022.zip"

if zip_url.startswith("<"):
    raise ValueError("Please replace the placeholder in `zip_url` with the actual URL to your zip file.")

# Set `force_download=True` to re-download even if a cached copy exists
force_download = False

downloads_dir = os.path.join(os.getcwd(), 'downloads')
os.makedirs(downloads_dir, exist_ok=True)
zip_filename = os.path.basename(zip_url)
local_zip_path = os.path.join(downloads_dir, zip_filename)

if not os.path.exists(local_zip_path) or force_download:
    print(f"Downloading: {zip_url}")
    with requests.get(zip_url, stream=True) as r:
        r.raise_for_status()
        with open(local_zip_path, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
    print(f"Saved ZIP to: {local_zip_path}")
else:
    print(f"Using cached ZIP: {local_zip_path}")

# Open the ZIP from disk (no re-download) and inspect contents
with zipfile.ZipFile(local_zip_path, 'r') as z:
    names = z.namelist()
    print("Files in archive:")
    for n in names:
        print(" -", n)

    # Find Excel files (.xlsx or .xls)
    xlsx_files = [n for n in names if n.lower().endswith(('.xlsx', '.xls'))]
    if not xlsx_files:
        raise ValueError("No Excel files found in the ZIP. Inspect `names` above and provide a ZIP that contains an Excel file.")

    # Use the first Excel file found
    file_in_zip = xlsx_files[0]
    print(f"\nReading Excel file '{file_in_zip}' from archive ...")
    data = z.read(file_in_zip)

# Read Excel and inspect sheets
xl = pd.ExcelFile(BytesIO(data))
sheet_names = xl.sheet_names
print("Sheets found:", sheet_names)

# Find and read the "GHG by NUTS2 and Sector" sheet, starting from row 6 (header)
target_sheet = "GHG by NUTS2 and Sector"
if target_sheet not in sheet_names:
    raise ValueError(f"Sheet '{target_sheet}' not found. Available sheets: {sheet_names}")

print(f"\nReading sheet '{target_sheet}' with header at row 6 ...")
df_ghg_sector = xl.parse(sheet_name=target_sheet, header=5)  # header=5 means row 6 (0-indexed)

# Helper to produce safe variable/filename names
def _safe_name(name):
    s = re.sub(r'[^0-9a-zA-Z_]', '_', name.strip())
    if not s:
        s = 'sheet'
    if s[0].isdigit():
        s = 's_' + s
    return s

base = os.path.splitext(os.path.basename(file_in_zip))[0]
var_name = f"{_safe_name(base)}__{_safe_name(target_sheet)}"

# Assign to globals so you can access the DataFrame by name in the notebook
globals()[var_name] = df_ghg_sector

# Save CSV copy
out_name = f"{base}__{_safe_name(target_sheet)}.csv"
out_path = os.path.join(os.getcwd(), out_name)
df_ghg_sector.to_csv(out_path, index=False)

print(f"Loaded sheet into variable: {var_name}")
print(f" - shape: {df_ghg_sector.shape}")
print(f"Saved CSV copy to: {out_path}")
print('\nPreview:')
display(df_ghg_sector.head())

"""## 3 ISPRA: Valle d'Aosta emissions (energy)"""

# Excel file URL
url = "https://indicatoriambientali.isprambiente.it/sites/default/files/indicatori_ambientali/2024-01-15/GHG%20ener_2023.xlsx"

# Download file in memory (no permanent saving)
response = requests.get(url)
response.raise_for_status()

# Load Excel file
xls = pd.ExcelFile(BytesIO(response.content))

# Choose the sheet (usually the first one, adjust if needed)
sheet_name = xls.sheet_names[0]
raw_df = pd.read_excel(xls, sheet_name=sheet_name, header=None)

# Find the header row containing both "REGIONI" and "Anni"
header_row = raw_df[
    raw_df.apply(
        lambda row: row.astype(str).str.contains("REGIONI", case=False).any()
        and row.astype(str).str.contains("Anni", case=False).any(),
        axis=1
    )
].index[0]

# Re-read the sheet using the detected header row
df = pd.read_excel(
    xls,
    sheet_name=sheet_name,
    header=header_row
)

# Optional: drop fully empty columns
df = df.dropna(axis=1, how="all")

df.head()

"""# Data preparation (cleaning, normalization, integration,  EDA)

## 1 Terna: electricity generation (by source)
"""

# EDA before cleaning

df = pd.read_sql_table("generation_y_r_p_s", engine, schema="back_tier")
ProfileReport(df, title="EDA Report", explorative=True).to_notebook_iframe()

# Filtering for production_type = 'Netta' (deleting 'Lorda')
# Aggregating production_type per source
# Aggregating production_type per province

with engine.begin() as conn:
    conn.execute(text("""
        DROP TABLE IF EXISTS back_tier.generation_y_r;
        CREATE TABLE back_tier.generation_y_r AS

        WITH province_agg AS
        (
            SELECT
                year,
                region,
                province,
                SUM(production_GWh) AS prod_province_sum
            FROM back_tier.generation_y_r_p_s
            WHERE production_type = 'Netta'
            GROUP BY year, region, province
        )

        SELECT
            year,
            region,
            SUM(prod_province_sum) AS production_GWh
        FROM province_agg
        GROUP BY year, region;
    """))

# Eda after cleaning

df = pd.read_sql_table("generation_y_r", engine, schema="back_tier")
ProfileReport(df, title="EDA Report", explorative=True).to_notebook_iframe()

# Regional distribution (fixed time)

year = 2022

df = pd.read_sql(
    f"""
    SELECT region, production_gwh
    FROM back_tier.generation_y_r
    WHERE year = {year}
    """,
    con=engine
)

fig = px.bar(
    df,
    x="region",
    y="production_gwh",
    title=f"Net electricity generation by region – year {year}",
    labels={"region": "Region", "production_gwh": "Generation (GWh)"}
)

fig.update_layout(
    width=800,
    height=800
)

fig.show()

# Yearly evolution (fixed region)

region = "Lombardia"

df = pd.read_sql(
    f"""
    SELECT year, production_gwh
    FROM back_tier.generation_y_r
    WHERE region = '{region}'
    ORDER BY year
    """,
    con=engine
)

fig = px.line(
    df,
    x="year",
    y="production_gwh",
    markers=True,
    title=f"Temporal evolution of net electricity generation – {region}",
    labels={"year": "Year", "production_gwh": "Generation (GWh)"}
)

fig.update_layout(
    width=800,
    height=800
)

fig.show()

# Time Comparison

year1 = 2005
year2 = 2022

df = pd.read_sql(
    f"""
    SELECT region, year, production_gwh
    FROM back_tier.generation_y_r
    WHERE year IN ({year1}, {year2})
    """,
    con=engine
)

# Pivot to wide format: one column per year
df_wide = df.pivot(index="region", columns="year", values="production_gwh").reset_index()

# Rename columns for readability
df_wide.columns = ["region", f"{year1}", f"{year2}"]

fig = px.bar(
    df_wide,
    x="region",
    y=[f"{year1}", f"{year2}"],
    barmode="group",
    title=f"Side‑by‑side comparison of regional net generation: {year1} vs {year2}",
    labels={"value": "Generation (GWh)", "region": "Region", "variable": "Year"}
)

fig.update_layout(
    width=1000,
    height= 800
)

fig.show()

# Region comparison

region1 = "Lombardia"
region2 = "Molise"

df = pd.read_sql(
    f"""
    SELECT year, region, production_gwh
    FROM back_tier.generation_y_r
    WHERE region IN ('{region1}', '{region2}')
    ORDER BY year, region
    """,
    con=engine
)

fig = px.line(
    df,
    x="year",
    y="production_gwh",
    color="region",
    markers=True,
    title=f"Temporal evolution of net electricity generation: {region1} vs {region2}",
    labels={
        "year": "Year",
        "production_gwh": "Generation (GWh)",
        "region": "Region"
    }
)

fig.update_layout(
    width=1000,
    height=800
)

fig.show()

"""## 2 EDGAR: ghg emissions (by sector)"""

# Eda before cleaning

df = pd.read_sql_table("emissions_r_s_ys", engine, schema="back_tier")
ProfileReport(df, title="EDA Report", explorative=True).to_notebook_iframe()

# Check available sectors and select only Italian dataframe
df_ghg_sector['Sector'].unique()
mask = df_ghg_sector['Country'] == 'Italy, San Marino and the Holy See'
ghg_italy = df_ghg_sector[mask]
display(ghg_italy)

#Drop Iso and Country columns of italian dataframe
ghg_italy = ghg_italy.drop(columns=['ISO','Country'])
display(ghg_italy)

#Check for missing values with missingno
#Note: Before 2012, Italy monitored industrial data on regional-base, that's why there is a lot of NaNs
msno.matrix(ghg_italy)

#We need regional data → drop rows where NUTS 2 desc = NaN
ghg_italy = ghg_italy.dropna(subset=['NUTS 2 desc'])  # Drop rows where NUTS_2_desc is NaN
display(ghg_italy)

#Upload ghg_italy to the database
ghg_italy.to_sql(
    "ghg_italy",
    engine,                         # your database engine
    schema='back_tier',             # specify the schema
    if_exists='replace',            # replace if table exists
    index=False                     # don't save index
)

# Aggregating Trento and Bolzano in Trentino
# Renaming valle d'aosta

# 1. Get all columns containing 'Y'
with engine.begin() as conn:
    ycols = conn.execute(text("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'emissions_r_s_ys'
          AND column_name ILIKE '%y%'
        ORDER BY column_name
    """)).fetchall()

ycols = [row[0] for row in ycols]

# 2. Build the SELECT list
select_cols = ['"NUTS 2 desc" AS region', '"Sector"'] + [f'"{c}"' for c in ycols]
select_clause = ", ".join(select_cols)

# 3. Create the new table
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS back_tier.emissions_energy_r_y"))

    conn.execute(text(f"""
        CREATE TABLE back_tier.emissions_energy_r_y AS
        SELECT {select_clause}
        FROM back_tier.emissions_r_s_ys
        WHERE "Sector" = 'Energy';
    """))

# Perform pivoting after cleaning process

# 1. Get all Y_ columns

with engine.begin() as conn:
    ycols = conn.execute(text("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'emissions_energy_r_y'
          AND column_name ILIKE 'y_%'
        ORDER BY column_name
    """)).fetchall()

ycols = [row[0] for row in ycols]

# 2. Build UNION ALL unpivot with correct column order
union_parts = []
for col in ycols:
    union_parts.append(
        f"""
        SELECT
            split_part('{col}', '_', 2)::int AS year,
            region,
            "{col}" AS emissions_ktco2eq
        FROM back_tier.emissions_energy_r_y
        """
    )

union_query = " UNION ALL ".join(union_parts)

# 3. Create the new emissions_y_r table with year filter and
with engine.begin() as conn:
    conn.execute(text(f"""
        DROP TABLE IF EXISTS back_tier.emissions_y_r;
        CREATE TABLE back_tier.emissions_y_r AS
        SELECT
            year,
            region_norm AS region,
            SUM(emissions_ktco2eq) AS emissions_ktco2eq
        FROM (
            SELECT
                year,
                CASE
                    WHEN region IN ('Provincia Autonoma di Bolzano/Bozen',
                                     'Provincia Autonoma di Trento')
                        THEN 'Trentino-Alto Adige'
                    WHEN region ILIKE '%Valle d''Aosta%'
                      OR region ILIKE '%Vallée d''Aoste%'
                        THEN 'Valle d''Aosta'
                    ELSE region
                END AS region_norm,
                emissions_ktco2eq
            FROM (
                {union_query}
            ) AS u
            WHERE year BETWEEN 2005 AND 2022
        ) AS normalized
        GROUP BY year, region_norm
        ORDER BY year, region_norm;
    """))

# Eda after cleaning

df = pd.read_sql_table("emissions_y_r_def", engine, schema="back_tier")
ProfileReport(df, title="EDA Report", explorative=True).to_notebook_iframe()

em = pd.read_sql("""
    SELECT year, region, emissions_ktco2eq
    FROM back_tier.emissions_y_r_def
    ORDER BY region, year
""", engine)

year1 = 2005
year2 = 2022

df_wide = em[em["year"].isin([year1, year2])].pivot(
    index="region",
    columns="year",
    values="emissions_ktco2eq"
).reset_index()

fig = px.bar(
    df_wide,
    x="region",
    y=[year1, year2],
    barmode="group",
    title=f"Confronto emissioni: {year1} vs {year2}",
    labels={
        "value": "Emissioni (ktCO₂eq)",
        "region": "Regione",
        "variable": "Anno"
    }
)

fig.update_layout(
    width=1000,
    height=800
)

fig.update_layout(xaxis_tickangle=45)
fig.show()

region1 = "Lombardia"
region2 = "Molise"

df2 = em[em["region"].isin([region1, region2])]

fig = px.line(
    df2,
    x="year",
    y="emissions_ktco2eq",
    color="region",
    markers=True,
    title=f"Temporal evolution of emissions: {region1} vs {region2}",
    labels={
        "year": "Year",
        "emissions_ktco2eq": "Emissions (ktCO₂eq)",
        "region": "Region"
    }
)

fig.update_layout(
    width=1000,
    height=800
)

fig.show()

# 2D Clustering

gen = pd.read_sql("""
    SELECT year, region, production_gwh
    FROM back_tier.generation_y_r
    WHERE year BETWEEN 2005 AND 2022
""", engine)

em = pd.read_sql("""
    SELECT year, region, emissions_ktco2eq
    FROM back_tier.emissions_y_r_def
    WHERE year BETWEEN 2005 AND 2022
""", engine)

year = 2021
df = pd.merge(gen, em, on=["region", "year"], how="inner")
dfy = df[df["year"] == year].copy()

X = dfy[["production_gwh", "emissions_ktco2eq"]]
kmeans = KMeans(n_clusters=3, random_state=42)
dfy["cluster"] = kmeans.fit_predict(X)

# Plot
fig = px.scatter(
    dfy,
    y="production_gwh",
    x="emissions_ktco2eq",
    color="cluster",
    text="region",
    title=f"Clustering of Regions – {year} Generation vs Emissions - Log scale",
    labels={
        "production_gwh": "Generation (GWh)",
        "emissions_ktco2eq": "Emissions (ktCO₂eq)",
        "cluster": "Cluster"
    },
    color_continuous_scale="Viridis"
)

fig.update_layout(
    width=1100,
    height=850,
    xaxis_type="log",
    yaxis_type="log"
)

fig.update_traces(
    marker=dict(size=18),
    textposition="top center"
)

fig.show()

"""## 3 ISPRA: Valle d'Aosta emissions (energy)"""

#Let's create a pandas df for Valle d'Aosta
Region = ["Valle d'Aosta"] * len(df.columns)
Region = Region[1:]

Year = df.iloc[0].values
Year = Year[1:]
Year = [int(y) for y in Year]

Emission = df.iloc[2].values
Emission = Emission[1:]
Emission = 1e-3 * Emission  # Convert to kt CO2eq

print(Region)
print(Year)
print(Emission)

#Create the dataframe
data = {
    "year": Year,
    "region": Region,
    "emissions_ktco2eq": Emission
}
df_VDA = pd.DataFrame(data)
display(df_VDA)

mock_year = []
for i in range(1990,2023):
    mock_year.append(i)

mock_emission = [0] * len(mock_year)
df_VDA_mock = pd.DataFrame({
    "year": mock_year,
    "region": ["Valle d'Aosta"] * len(mock_year),
    "emissions_ktco2eq": mock_emission
})

#I want to do a join to enhance df_VDA with df_VDA_mock, so that I have all years from 1990 to 2022, filling missing emissions with 0
df_VDA_enhanced = pd.merge(df_VDA_mock, df_VDA, on=["region", "year"], how="left", suffixes=('_mock', ''))
df_VDA_enhanced["emissions_ktco2eq"] = df_VDA_enhanced["emissions_ktco2eq"].fillna(df_VDA_enhanced["emissions_ktco2eq_mock"])
df_VDA_enhanced = df_VDA_enhanced.drop(columns=["emissions_ktco2eq_mock"])

#Substitute 0 with Null
df_VDA_enhanced["emissions_ktco2eq"] = df_VDA_enhanced["emissions_ktco2eq"].replace(0, np.nan)

#Cut the dataframe to years 2005-2022
df_VDA_enhanced = df_VDA_enhanced[(df_VDA_enhanced["year"] >= 2005) & (df_VDA_enhanced["year"] <= 2022)]
display(df_VDA_enhanced)

# Upload df_VDA_enhanced to Neon
df_VDA_enhanced.to_sql(
    'ghg_emissioni_valle_daosta',  # table name
    engine,                         # your database engine
    schema='back_tier',             # specify the schema
    if_exists='replace',            # replace if table exists
    index=False                     # don't save index
)

# Data enrichment of ISPRA (Valle d'Aosta) on EDGAR

with engine.connect() as conn:
    conn.execute(text(
    """
    CREATE TABLE IF NOT EXISTS back_tier.emissions_y_r_def AS
    SELECT
        year,
        region,
        emissions_ktco2eq
    FROM back_tier.emissions_y_r

    UNION ALL

    SELECT
        year,
        region,
        emissions_ktco2eq
    FROM back_tier.ghg_emissioni_valle_daosta;
    """))
    conn.commit()

"""## Final integration and fact table creation for star schema"""

# Integrating the two cleaned dataset into the final dataset containing carbon emission intensity

with engine.begin() as conn:
    conn.execute(text("""
CREATE TABLE back_tier.carbon_emission_intensity AS
SELECT
    g.year,
    g.region,
    (e.emissions_ktco2eq / g.production_gwh) AS carbon_emission_intensity
FROM back_tier.generation_y_r AS g
JOIN back_tier.emissions_y_r_def AS e
    ON g.year = e.year
    AND g.region = e.region
ORDER BY g.year, g.region;
"""))

# Fact table creation

with engine.begin() as conn:
    conn.execute(text("""
CREATE TABLE front_tier.fact_table AS
SELECT
    dy."id" AS year_id,
    dr."id" AS region_id,
    cei.carbon_emission_intensity
FROM back_tier.carbon_emission_intensity AS cei
JOIN front_tier."Year_index" AS dy ON cei.year = dy."Year"
JOIN front_tier."Region_index" AS dr ON cei.region = dr."Region"
ORDER BY year_id, region_id;
"""))

"""# Data analysis"""

# Carbon emission intensity data analysis

# Function to add bars + rank labels
def add_bar_with_labels(df_year, color, row, col):
    fig.add_trace(
        go.Bar(
            x=df_year["carbon_emission_intensity"],
            y=df_year["region"],
            orientation="h",
            marker_color=color,
            text=df_year["rank"],
            textposition="outside",
            textfont=dict(color="black", size=12)
        ),
        row=row, col=col
    )

# Function to compute the rank (1 = lowest value, NaN = 0)
def compute_rank(df_year):
    r = df_year["carbon_emission_intensity"].rank(method="dense", ascending=True)
    r = r.fillna(0).astype(int)
    return r

df = pd.read_sql_query("""
SELECT
    f.year_id,
    dy."Year" AS year,
    f.region_id,
    dr."Region" AS region,
    f.carbon_emission_intensity
FROM front_tier.fact_table AS f
JOIN front_tier."Year_index" AS dy
    ON f.year_id = dy."id"
JOIN front_tier."Region_index" AS dr
    ON f.region_id = dr."id"
ORDER BY dy."Year", dr."Region";
""", engine)

df_2005 = df[df["year"] == 2005].sort_values("carbon_emission_intensity", ascending=False)
df_2015 = df[df["year"] == 2015].sort_values("carbon_emission_intensity", ascending=False)
df_2022 = df[df["year"] == 2022].sort_values("carbon_emission_intensity", ascending=False)

df_2005["rank"] = compute_rank(df_2005)
df_2015["rank"] = compute_rank(df_2015)
df_2022["rank"] = compute_rank(df_2022)

fig = make_subplots(
    rows=1, cols=3,
    shared_yaxes=True,
    horizontal_spacing=0.03,
    subplot_titles=("2005", "2015", "2022")
)

add_bar_with_labels(df_2005, "#4C72B0", 1, 1)
add_bar_with_labels(df_2015, "#55A868", 1, 2)
add_bar_with_labels(df_2022, "#C44E52", 1, 3)

fig.update_layout(
    height=600,
    width=1000,
    showlegend=False,
    title_text="Regional emissions ranking: 2005 vs 2015 vs 2022",
    title_x=0.5
)

for i in range(1, 4):
    fig.update_xaxes(range=[0, 1.6], row=1, col=i)

fig.add_annotation(
    x=0.5, y=-0.12,
    xref="paper", yref="paper",
    text="Carbon Emission Intensity (ktCO₂eq/GWh)",
    showarrow=False,
    font=dict(size=16)
)


mean_2005 = df_2005["carbon_emission_intensity"].mean()
mean_2015 = df_2015["carbon_emission_intensity"].mean()
mean_2022 = df_2022["carbon_emission_intensity"].mean()


fig.add_vline(
    x=mean_2005,
    line_width=2,
    line_dash="dash",
    line_color="black",
    row=1, col=1
)

fig.add_vline(
    x=mean_2015,
    line_width=2,
    line_dash="dash",
    line_color="black",
    row=1, col=2
)

fig.add_vline(
    x=mean_2022,
    line_width=2,
    line_dash="dash",
    line_color="black",
    row=1, col=3
)

fig.add_annotation(
    x=mean_2005, y=1.05,
    xref="x1", yref="paper",
    text=f"{mean_2005:.2f}",
    showarrow=False,
    font=dict(size=12, color="black")
)

fig.add_annotation(
    x=mean_2015, y=1.05,
    xref="x2", yref="paper",
    text=f"{mean_2015:.2f}",
    showarrow=False,
    font=dict(size=12, color="black")
)

fig.add_annotation(
    x=mean_2022, y=1.05,
    xref="x3", yref="paper",
    text=f"{mean_2022:.2f}",
    showarrow=False,
    font=dict(size=12, color="black")
)

fig.show()

# GEOJSON
url = "https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson"
italy_regions = requests.get(url).json()

# Centroids
centroids = {}
for feature in italy_regions["features"]:
    geom = shape(feature["geometry"])
    lon, lat = geom.centroid.x, geom.centroid.y
    name = feature["properties"]["reg_name"]
    centroids[name] = (lat, lon)

# Percentage variation
df_pivot = df.pivot(index="region", columns="year", values="carbon_emission_intensity")
df_pivot = df_pivot.reindex(sorted(df_pivot.columns), axis=1)
df_pivot = df_pivot.apply(pd.to_numeric, errors="coerce")
annual_pct_change = 100 * df_pivot.diff(axis=1) / df_pivot.shift(axis=1)

# Average and cumulative calculus
df_mean = annual_pct_change.mean(axis=1, skipna=True).reset_index()
df_mean.columns = ["region", "mean_speed"]
df_mean["mean_speed"] = df_mean["mean_speed"].fillna(0)

df_cumulative = annual_pct_change.sum(axis=1, skipna=True).reset_index()
df_cumulative.columns = ["region", "cumulative_change"]
df_cumulative["cumulative_change"] = df_cumulative["cumulative_change"].fillna(0)

# Normalization for region and names only for data visualization purpouse
df_mean["region"] = df_mean["region"].replace({
    "Trentino-Alto Adige": "Trentino-Alto Adige/Südtirol",
    "Valle d'Aosta": "Valle d'Aosta/Vallée d'Aoste",
    "Valle d’Aosta": "Valle d'Aosta/Vallée d'Aoste",
})

df_cumulative["region"] = df_cumulative["region"].replace({
    "Trentino-Alto Adige": "Trentino-Alto Adige/Südtirol",
    "Valle d'Aosta": "Valle d'Aosta/Vallée d'Aoste",
    "Valle d’Aosta": "Valle d'Aosta/Vallée d'Aoste",
})

# Plot
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Average Annual % Change", "Cumulative Annual % Change"),
    specs=[[{"type": "choropleth"}, {"type": "choropleth"}]],
    horizontal_spacing=0.05
)

# Average Map
fig.add_trace(
    go.Choropleth(
        geojson=italy_regions,
        featureidkey="properties.reg_name",
        locations=df_mean["region"],
        z=df_mean["mean_speed"],
        colorscale=[[0, "#55A868"], [1, "#C44E52"]],
        colorbar=dict(title="Mean %", x=0.42, len=0.75),
        marker_line_width=0.5,
        marker_line_color="black"
    ),
    row=1, col=1
)

# Cumulative map
fig.add_trace(
    go.Choropleth(
        geojson=italy_regions,
        featureidkey="properties.reg_name",
        locations=df_cumulative["region"],
        z=df_cumulative["cumulative_change"],
        colorscale=[[0, "#55A868"], [1, "#C44E52"]],
        colorbar=dict(title="Cumulative %", x=1.02, len=0.75),
        marker_line_width=0.5,
        marker_line_color="black"
    ),
    row=1, col=2
)

# Labels
fig.add_trace(
    go.Scattergeo(
        lat=[centroids[r][0] for r in df_mean["region"]],
        lon=[centroids[r][1] for r in df_mean["region"]],
        text=[f"<span style='background-color:rgba(255,255,255,0.7);"
              f"padding:2px;border-radius:3px'>{v:.1f}</span>"
              for v in df_mean["mean_speed"]],
        mode="text",
        textfont=dict(size=12, color="black"),
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scattergeo(
        lat=[centroids[r][0] for r in df_cumulative["region"]],
        lon=[centroids[r][1] for r in df_cumulative["region"]],
        text=[f"<span style='background-color:rgba(255,255,255,0.7);"
              f"padding:2px;border-radius:3px'>{v:.1f}</span>"
              for v in df_cumulative["cumulative_change"]],
        mode="text",
        textfont=dict(size=12, color="black"),
    ),
    row=1, col=2
)

# Custom projection for better visualization
fig.update_geos(
    visible=False,
    projection_type="mercator",
    projection_scale=1,
    center=dict(lat=42.5, lon=12.5),
    domain=dict(x=[0.00, 0.50], y=[0.00, 1.00]),
    row=1, col=1
)

fig.update_geos(
    visible=False,
    projection_type="mercator",
    projection_scale=1,
    center=dict(lat=42.5, lon=12.5),
    domain=dict(x=[0.50, 1.00], y=[0.00, 1.00]),
    row=1, col=2
)

fig.update_layout(
    height=700,
    width=1200,
    margin=dict(l=0, r=0, t=80, b=0),
)

fig.show()